"""Add image_url to projects table

Revision ID: 1469c6ab3828
Revises: baseline_2026_01_28
Create Date: 2026-01-28 19:17:31.993243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1469c6ab3828'
down_revision: Union[str, Sequence[str], None] = 'baseline_2026_01_28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_column('about', 'skills')
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.add_column('projects', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'image_url')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.add_column('about', sa.Column('skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
